name: sdf
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.*
    - numpy
    - tqdm
    - matplotlib
    - seaborn
    - pandas
    - scikit-fmm
    - pip
    - pip:
      - mitsuba
      - fastsweep